#ifndef _SHMEM_CONSTANTS_H
#define _SHMEM_CONSTANTS_H
#include <limits.h>

enum ErrorType : int {
    SHMEM_SUCCESS = 0,
    ERROR_INVALID_PARAM,
    ERROR_INVALID_VALUE,
    ERROR_SMEM_ERROR
};

enum {
    SHMEM_STATUS_NOT_INITALIZED = 0,
    SHMEM_STATUS_SHM_CREATED,
    SHMEM_STATUS_IS_INITALIZED,
    SHMEM_STATUS_INVALID = INT_MAX,
};

#endif /*SHMEM_CONSTANTS*/